resources:
- portal-eol.yaml
- ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: portal
  newName: ghcr.io/eol-uchile/portal-eol
  newTag: 8f269a2e87dd5a0483e6cbcfedd31a90a5d23664
