apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- configmap.yaml
- deployment.yaml
- ingress.yaml
- service.yaml
- serviceaccount.yaml
- pvc.yaml
- postgresql/
- redis/
- secrets/weblate.yaml
- secrets/postgres-env.yaml
- secrets/redis-env.yaml
- secrets/postgres-file.yaml
- secrets/redis-file.yaml
